In [24]:
import pandas as pd 
import numpy as np

In [25]:
#Initialise a dataframe to Full.csv in data folder
df = pd.read_csv('Data/Full.csv')

In [26]:
# Drop all columns that contain the string "Unnamed" in their name
df = df.drop(df.filter(regex='Unnamed').columns, axis=1)

In [27]:
df

,Sl. No.,Patent Application No.,Status of Patent (Published / Granted),Inventor/s Name,Title of the Patent,Applicant/s Name,Patent Filed Date (DD/MM/YYYY),Patent Published Date / Granted Date (DD/MM/YYYY),Patent Publication Number / Patent Granted Number,Assignee/s Name (Institute Affiliation/s at time of Appication),"Here, attach Source Proof Screenshots/URL/ Website Links, etc.",Department,Country,MAapping with SDG,Link of SDG Document
0,2020.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1.0,2315/MUM/2011,Granted,Dr. Prasad D. Khandekar,Pass Transistor Adiabatic Circuit With Stand- ...,Dr. Prasad D. Khandekar,17-08-2011,17-12-2020,353941,Vishwakarma Institute of Information Technolog...,https://drive.google.com/file/d/1k_mzGREKOL4uP...,Electrical and Electronics Engineering,India,"7,9,11,12,13",https://docs.google.com/document/d/16KGjPIDijs...
2,2.0,202021008633,Granted,"TIWARI, Meenakshi M.; JADHAV, Vikrant V.; THOT...",Loop device for a plurality of teeth,"TIWARI, Meenakshi M.; JADHAV, Vikrant V.; THOT...",28-02-2020,27-11-2020,352515,Dr.Vishwanath Karad MIT WORLD PEACE UNIVERSITY...,https://drive.google.com/file/d/1pAAiPHddW_vaK...,Mechanical Engineering,India,"3,9,10,12",https://docs.google.com/document/d/1M9fkxE7w2m...
3,3.0,2183/MUM/2012,Granted,"Vivek Deshpande, Archana Khandekar(Dhoke)",Process for estimation of flow rate to control...,Vivek Deshpande,7/31/2012,22-06-2020,339009,Dr.Vishwanath Karad MIT WORLD PEACE UNIVERSITY...,https://drive.google.com/file/d/1YLRIo1pGA6gZg...,Computer Engineering & Technology,India,"9,12,7,11,13",https://docs.google.com/document/d/1X4gQlJoRGN...
4,4.0,2020102377,Granted,"Jeevan Pise, Priya; Kamble, Sachin Ramchandra;...",Water collection & notification intelligent ma...,"Jeevan Pise, Priya; Kamble, Sachin Ramchandra;...",23-09-2020,10/21/2020,2020102377,Dr.Vishwanath Karad MIT WORLD PEACE UNIVERSITY...,https://drive.google.com/file/d/1nZIbix1oDSneW...,Civil Engineering,Australia,"6,7,9,11,12,13,17",https://docs.google.com/document/d/17UAsRzMoPR...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
960,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
961,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
962,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
963,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
964,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [33]:
#Delete rows with all NaN values
df = df.dropna(how='all')
df

,Sl. No.,Patent Application No.,Status of Patent (Published / Granted),Inventor/s Name,Title of the Patent,Applicant/s Name,Patent Filed Date (DD/MM/YYYY),Patent Published Date / Granted Date (DD/MM/YYYY),Patent Publication Number / Patent Granted Number,Assignee/s Name (Institute Affiliation/s at time of Appication),"Here, attach Source Proof Screenshots/URL/ Website Links, etc.",Department,Country,MAapping with SDG,Link of SDG Document
0,2020.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1.0,2315/MUM/2011,Granted,Dr. Prasad D. Khandekar,Pass Transistor Adiabatic Circuit With Stand- ...,Dr. Prasad D. Khandekar,17-08-2011,17-12-2020,353941,Vishwakarma Institute of Information Technolog...,https://drive.google.com/file/d/1k_mzGREKOL4uP...,Electrical and Electronics Engineering,India,"7,9,11,12,13",https://docs.google.com/document/d/16KGjPIDijs...
2,2.0,202021008633,Granted,"TIWARI, Meenakshi M.; JADHAV, Vikrant V.; THOT...",Loop device for a plurality of teeth,"TIWARI, Meenakshi M.; JADHAV, Vikrant V.; THOT...",28-02-2020,27-11-2020,352515,Dr.Vishwanath Karad MIT WORLD PEACE UNIVERSITY...,https://drive.google.com/file/d/1pAAiPHddW_vaK...,Mechanical Engineering,India,"3,9,10,12",https://docs.google.com/document/d/1M9fkxE7w2m...
3,3.0,2183/MUM/2012,Granted,"Vivek Deshpande, Archana Khandekar(Dhoke)",Process for estimation of flow rate to control...,Vivek Deshpande,7/31/2012,22-06-2020,339009,Dr.Vishwanath Karad MIT WORLD PEACE UNIVERSITY...,https://drive.google.com/file/d/1YLRIo1pGA6gZg...,Computer Engineering & Technology,India,"9,12,7,11,13",https://docs.google.com/document/d/1X4gQlJoRGN...
4,4.0,2020102377,Granted,"Jeevan Pise, Priya; Kamble, Sachin Ramchandra;...",Water collection & notification intelligent ma...,"Jeevan Pise, Priya; Kamble, Sachin Ramchandra;...",23-09-2020,10/21/2020,2020102377,Dr.Vishwanath Karad MIT WORLD PEACE UNIVERSITY...,https://drive.google.com/file/d/1nZIbix1oDSneW...,Civil Engineering,Australia,"6,7,9,11,12,13,17",https://docs.google.com/document/d/17UAsRzMoPR...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
437,432.0,202521070423,Published,"AKSHAY MOTILAL BAHETI, ANIL TUKARAM PAWAR, AMO...",A PHARMACEUTICAL COMPOSITION FOR ANALGESIC AND...,Dr. Vishwanath Karad MIT- World Peace University,7/24/2025,8/15/2025,33/2025,Dr. Vishwanath Karad MIT World Peace University,https://drive.google.com/file/d/17_22h5X-BKXVs...,Pharmacy,India,"3,9,12",https://docs.google.com/document/d/1RCYg21gx71...
438,433.0,202521071566,Published,"ADVAIT KULKARNI, PRATHAMESH MARNE, SHREYA HEMA...",A METHOD FOR PREPARING AN HERBAL TEA FORMULATION,Dr. Vishwanath Karad MIT- World Peace University,7/28/2025,8/15/2025,33/2025,Dr. Vishwanath Karad MIT World Peace University,https://drive.google.com/file/d/1FMfLEkTmZ4xPu...,Pharmacy,India,"3,9,12",https://docs.google.com/document/d/1IlOQvdcTAn...
439,434.0,202521071563,Published,"AKSHAY MOTILAL BAHETI, ANIL TUKARAM PAWAR, AMO...",METHOD FOR FORMULATION OF AN ENTERIC COATED HE...,Dr. Vishwanath Karad MIT- World Peace University,7/28/2025,8/8/2025,32/2025,Dr. Vishwanath Karad MIT World Peace University,https://drive.google.com/file/d/1Mg-a1GtQOP0QL...,Pharmacy,India,"3,9,12",https://docs.google.com/document/d/1jPsZ_gciZ9...
440,435.0,202521097069,Published,"DR. VIJAYAPANDI PANDY, MS. DNYANESHWARI DHANAJ...",AN ELEVATED MAZE APPARATUS FOR RATS,Dr. Vishwanath Karad MIT- World Peace University,10/8/2025,10/24/2025,43/2025,Dr. Vishwanath Karad MIT World Peace University,https://drive.google.com/file/d/1qNEzEiOhdGZvD...,Pharmacy,India,"3,4,9",https://docs.google.com/document/d/13SkaLFaA9g...
441,436.0,202521097070,Published,"DR. VIJAYAPANDI PANDY, MS. DNYANESHWARI DHANAJ...",AN ELEVATED MAZE APPARATUS FOR MICE,Dr. Vishwanath Karad MIT- World Peace University,10/8/2025,10/24/2025,43/2025,Dr. Vishwanath Karad MIT World Peace University,https://drive.google.com/file/d/1xZ1Z4q9hys4nD...,Pharmacy,India,"3,4,9",https://docs.google.com/document/d/1pL6nA3GVME...

In [34]:
#Updating the csv file after cleaning
df.to_csv('Data/Full_Cleaned.csv', index=False)

In [36]:
#Add a column Year in dataframe store null for now
df['Year'] = np.nan

C:\Users\hp\AppData\Local\Temp\ipykernel_13696\3916440362.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Year'] = np.nan

In [37]:
year = 2020
for i in range(len(df)):
    if df.iloc[i]['Sl. No.'] > year:
        year = year + 1
    df.at[i, 'Year'] = year

In [38]:
df

,Sl. No.,Patent Application No.,Status of Patent (Published / Granted),Inventor/s Name,Title of the Patent,Applicant/s Name,Patent Filed Date (DD/MM/YYYY),Patent Published Date / Granted Date (DD/MM/YYYY),Patent Publication Number / Patent Granted Number,Assignee/s Name (Institute Affiliation/s at time of Appication),"Here, attach Source Proof Screenshots/URL/ Website Links, etc.",Department,Country,MAapping with SDG,Link of SDG Document,Year
0,2020.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2020.0
1,1.0,2315/MUM/2011,Granted,Dr. Prasad D. Khandekar,Pass Transistor Adiabatic Circuit With Stand- ...,Dr. Prasad D. Khandekar,17-08-2011,17-12-2020,353941,Vishwakarma Institute of Information Technolog...,https://drive.google.com/file/d/1k_mzGREKOL4uP...,Electrical and Electronics Engineering,India,"7,9,11,12,13",https://docs.google.com/document/d/16KGjPIDijs...,2020.0
2,2.0,202021008633,Granted,"TIWARI, Meenakshi M.; JADHAV, Vikrant V.; THOT...",Loop device for a plurality of teeth,"TIWARI, Meenakshi M.; JADHAV, Vikrant V.; THOT...",28-02-2020,27-11-2020,352515,Dr.Vishwanath Karad MIT WORLD PEACE UNIVERSITY...,https://drive.google.com/file/d/1pAAiPHddW_vaK...,Mechanical Engineering,India,"3,9,10,12",https://docs.google.com/document/d/1M9fkxE7w2m...,2020.0
3,3.0,2183/MUM/2012,Granted,"Vivek Deshpande, Archana Khandekar(Dhoke)",Process for estimation of flow rate to control...,Vivek Deshpande,7/31/2012,22-06-2020,339009,Dr.Vishwanath Karad MIT WORLD PEACE UNIVERSITY...,https://drive.google.com/file/d/1YLRIo1pGA6gZg...,Computer Engineering & Technology,India,"9,12,7,11,13",https://docs.google.com/document/d/1X4gQlJoRGN...,2020.0
4,4.0,2020102377,Granted,"Jeevan Pise, Priya; Kamble, Sachin Ramchandra;...",Water collection & notification intelligent ma...,"Jeevan Pise, Priya; Kamble, Sachin Ramchandra;...",23-09-2020,10/21/2020,2020102377,Dr.Vishwanath Karad MIT WORLD PEACE UNIVERSITY...,https://drive.google.com/file/d/1nZIbix1oDSneW...,Civil Engineering,Australia,"6,7,9,11,12,13,17",https://docs.google.com/document/d/17UAsRzMoPR...,2020.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
437,432.0,202521070423,Published,"AKSHAY MOTILAL BAHETI, ANIL TUKARAM PAWAR, AMO...",A PHARMACEUTICAL COMPOSITION FOR ANALGESIC AND...,Dr. Vishwanath Karad MIT- World Peace University,7/24/2025,8/15/2025,33/2025,Dr. Vishwanath Karad MIT World Peace University,https://drive.google.com/file/d/17_22h5X-BKXVs...,Pharmacy,India,"3,9,12",https://docs.google.com/document/d/1RCYg21gx71...,2025.0
438,433.0,202521071566,Published,"ADVAIT KULKARNI, PRATHAMESH MARNE, SHREYA HEMA...",A METHOD FOR PREPARING AN HERBAL TEA FORMULATION,Dr. Vishwanath Karad MIT- World Peace University,7/28/2025,8/15/2025,33/2025,Dr. Vishwanath Karad MIT World Peace University,https://drive.google.com/file/d/1FMfLEkTmZ4xPu...,Pharmacy,India,"3,9,12",https://docs.google.com/document/d/1IlOQvdcTAn...,2025.0
439,434.0,202521071563,Published,"AKSHAY MOTILAL BAHETI, ANIL TUKARAM PAWAR, AMO...",METHOD FOR FORMULATION OF AN ENTERIC COATED HE...,Dr. Vishwanath Karad MIT- World Peace University,7/28/2025,8/8/2025,32/2025,Dr. Vishwanath Karad MIT World Peace University,https://drive.google.com/file/d/1Mg-a1GtQOP0QL...,Pharmacy,India,"3,9,12",https://docs.google.com/document/d/1jPsZ_gciZ9...,2025.0
440,435.0,202521097069,Published,"DR. VIJAYAPANDI PANDY, MS. DNYANESHWARI DHANAJ...",AN ELEVATED MAZE APPARATUS FOR RATS,Dr. Vishwanath Karad MIT- World Peace University,10/8/2025,10/24/2025,43/2025,Dr. Vishwanath Karad MIT World Peace University,https://drive.google.com/file/d/1qNEzEiOhdGZvD...,Pharmacy,India,"3,4,9",https://docs.google.com/document/d/13SkaLFaA9g...,2025.0
441,436.0,202521097070,Published,"DR. VIJAYAPANDI PANDY, MS. DNYANESHWARI DHANAJ...",AN ELEVATED MAZE APPARATUS FOR MICE,Dr. Vishwanath Karad MIT- World Peace University,10/8/2025,10/24/2025,43/2025,Dr. Vishwanath Karad MIT World Peace University,https://drive.google.com/file/d/1xZ1Z4q9hys4nD...,Pharmacy,India,"3,4,9",https://docs.google.com/document/d/1pL6nA3GVME...,2025.0

In [42]:
#delete rows with Sl. No. as 2020,2021,2022,2023,2024 and 2025
df = df[~df['Sl. No.'].isin([2020, 2021, 2022, 2023, 2024, 2025])]

In [44]:
#Updating the csv file after cleaning
df.to_csv('Data/Full_Cleaned.csv', index=False)

In [ ]:
# #display th entire dataframe
# pd.set_option('display.max_rows', None)
# df

,Sl. No.,Patent Application No.,Status of Patent (Published / Granted),Inventor/s Name,Title of the Patent,Applicant/s Name,Patent Filed Date (DD/MM/YYYY),Patent Published Date / Granted Date (DD/MM/YYYY),Patent Publication Number / Patent Granted Number,Assignee/s Name (Institute Affiliation/s at time of Appication),"Here, attach Source Proof Screenshots/URL/ Website Links, etc.",Department,Country,MAapping with SDG,Link of SDG Document,Year
1,1.0,2315/MUM/2011,Granted,Dr. Prasad D. Khandekar,Pass Transistor Adiabatic Circuit With Stand- ...,Dr. Prasad D. Khandekar,17-08-2011,17-12-2020,353941,Vishwakarma Institute of Information Technolog...,https://drive.google.com/file/d/1k_mzGREKOL4uP...,Electrical and Electronics Engineering,India,"7,9,11,12,13",https://docs.google.com/document/d/16KGjPIDijs...,2020.0
2,2.0,202021008633,Granted,"TIWARI, Meenakshi M.; JADHAV, Vikrant V.; THOT...",Loop device for a plurality of teeth,"TIWARI, Meenakshi M.; JADHAV, Vikrant V.; THOT...",28-02-2020,27-11-2020,352515,Dr.Vishwanath Karad MIT WORLD PEACE UNIVERSITY...,https://drive.google.com/file/d/1pAAiPHddW_vaK...,Mechanical Engineering,India,"3,9,10,12",https://docs.google.com/document/d/1M9fkxE7w2m...,2020.0
3,3.0,2183/MUM/2012,Granted,"Vivek Deshpande, Archana Khandekar(Dhoke)",Process for estimation of flow rate to control...,Vivek Deshpande,7/31/2012,22-06-2020,339009,Dr.Vishwanath Karad MIT WORLD PEACE UNIVERSITY...,https://drive.google.com/file/d/1YLRIo1pGA6gZg...,Computer Engineering & Technology,India,"9,12,7,11,13",https://docs.google.com/document/d/1X4gQlJoRGN...,2020.0
4,4.0,2020102377,Granted,"Jeevan Pise, Priya; Kamble, Sachin Ramchandra;...",Water collection & notification intelligent ma...,"Jeevan Pise, Priya; Kamble, Sachin Ramchandra;...",23-09-2020,10/21/2020,2020102377,Dr.Vishwanath Karad MIT WORLD PEACE UNIVERSITY...,https://drive.google.com/file/d/1nZIbix1oDSneW...,Civil Engineering,Australia,"6,7,9,11,12,13,17",https://docs.google.com/document/d/17UAsRzMoPR...,2020.0
5,5.0,2020101867,Granted,"Dr. Krishna Warhade, C.T., MANIMEGALAI; R., RA...",Design and Implementation of a disaster manage...,"C.T., MANIMEGALAI; R., RAJU; S., RAMESH; N., V...",18-08-2020,9/9/2020,2020101867,Dr.Vishwanath Karad MIT WORLD PEACE UNIVERSITY...,https://drive.google.com/file/d/17qQt5wfX37pRa...,Electrical and Electronics Engineering,Australia,"11,9,13,3,17,7",https://docs.google.com/document/d/1ihmFAQRanW...,2020.0
6,6.0,202021024989,Published,"Dr Atul Prabhakar Kulkarni, Dr Pravin Popat Hu...",Design and development of innovative spatters ...,Dr Pravin Popat Hujare,15-06-2020,10-07-2020,28/2020,Dr.Vishwanath Karad MIT WORLD PEACE UNIVERSITY...,https://drive.google.com/file/d/1MgfkiElFe_9b4...,Mechanical Engineering,India,"9,12,8,13,11",https://docs.google.com/document/d/10D09X06aH7...,2020.0
7,7.0,202021007685,Published,"SUCHITRA AMOL KHOJE, SANJAY BHAGWAN MOHITE",Safety System For Drainage Gas Monitoring,"SUCHITRA AMOL KHOJE, SANJAY BHAGWAN MOHITE",24-02-2020,3/6/2020,10/2020,Dr.Vishwanath Karad MIT WORLD PEACE UNIVERSITY...,https://drive.google.com/file/d/17Gl7DmYYHl9Ze...,Electrical and Electronics Engineering,India,"3,8,9,11,12,13",https://docs.google.com/document/d/1Y2lh9iqbf_...,2020.0
8,8.0,202021007681,Published,"SANJAY BHAGWAN MOHITE, SUCHITRA AMOL KHOJE",Smart Crop Disease Detection And Treatment System,"SANJAY BHAGWAN MOHITE, SUCHITRA AMOL KHOJE",24-02-2020,3/6/2020,10/2020,Dr.Vishwanath Karad MIT WORLD PEACE UNIVERSITY...,https://drive.google.com/file/d/1xrD_xK10rqSdY...,Electrical and Electronics Engineering,India,"2,9,12,13,8,15",https://docs.google.com/document/d/1cgevnyt5es...,2020.0
9,9.0,202021043072,Published,Dr Mrudula S Kulkarni,Development of Thermal conductivity and maturi...,Dr Sumant N Shinde Dr. H. R. MagarPatil,04-10-2020,09-10-2020,41/2020,Dr.Vishwanath Karad MIT WORLD PEACE UNIVERSITY...,https://drive.google.com/file/d/1SL1UhMbtlJfRU...,Civil Engineering,India,"9,11,12,13,7,4",https://docs.google.com/document/d/1gxiZPsfXk5...,2020.0
10,10.0,201921053124,Published,"Prafulla Bansod, Ravindra Gaikwad, Shyam Kodape",Two Layer membrane Model for separation of Car...,"Shrikant Barkade, Dinesh Bhutada, Prafulla Ban...",20-12-2019,03-01-2020,01/2020,Dr.Vishwanath Karad MIT WORLD PEACE UNIVERSITY...,https://drive.google.com/file/d/11bQoA5xWGvfJa...,Chemical Engineering,India,"3,7,9,12,13,15,2",https://docs.google.com/document/d/1jAcZJAP_Gr...,2020.0
11,11.0,202021034153,Published,"Aditya Sanjay Mhaske, Atharv Satish Nikam, San...",Smart glasses for monocular vision,"Aditya Sanjay Mhaske, Atharv Satish Nikam, San...",10-08-2020,8/21/2020,34/2020,Dr.Vishwanath Karad MIT WORLD PEACE UNIVERSITY...,https://drive.google.com/file/d/13xxOToZxZV2Xy...,Computer Engineering & Technology,India,"3,8,9,10,11,4,12",https://docs.google.com/document/d/1OQuHduwGOY...,2020.0
12,12.0,202021030782,Published,"Shalaka Vardhaman Tiwatane, Vardhaman Pitambar...",DESIGN AND DEVELOPMENT OF PUBLIC ROAD TRANSPOR...,"Shalaka Vardhaman Tiwatane, Vardhaman Pitambar...",20-07-2020,28-08-2020,35/2020,Dr.Vishwanath Karad MIT WORLD PEACE UNIVERSITY...,https://drive.google.com/file/d/1BWYIexWF6xWmV...,Computer Engineering & Technology,India,"3,11,8,9,10,12,17",https://docs.google.com/document/d/1zFjCyaaQ22...,2020.0
13,13.0,202021040241,Published,"Mr. Vivekanand A Naikwadi, Dr.Amit Jomde, Mr.T...",Design and development of innovative radiator ...,"Mr. Vivekanand A Naikwadi, Dr.Amit Jomde, Mr.T...",17-09-2020,25-09-2020,39/2020,Dr.Vishwanath Karad MIT WORLD PEACE UNIVERSITY...,https://drive.google.com/file/d/1-oUStQWMZXrus...,Mechanical Engineering,India,"9,12,13,8,3,7",https://docs.google.com/document/d/1QVjqFtZxWZ...,2020.0
14,14.0,201921051720,Published,"Harshita Bhorshetti, Shreyas Ghuge, Sukhada Bh...",SMART GLASSES FOR THE VISUALLY IMPAIRED PEOPLE,"Harshita Bhorshetti, Shreyas Ghuge, Sukhada Bh...",13-12-2019,03-01-2020,01/2020,Dr.Vishwanath Karad MIT WORLD PEACE UNIVERSITY...,https://drive.google.com/file/d/1O2jf2SA-G_4XY...,Electrical and Electronics Engineering,India,"3,10,9,8,4,11",https://docs.google.com/document/d/1_TAxoaBAjl...,2020.0
15,15.0,202021033067,Published,"Dr Pravin Popat Hujare, Mr.Manas Anand Kulkarn...",Design and development of compact aloe vera ge...,"Dr Pravin Popat Hujare, Dr.Deepak Popat Hujare...",01-08-2020,28-08-2020,35/2020,Dr.Vishwanath Karad MIT WORLD PEACE UNIVERSITY...,https://drive.google.com/file/d/175h2gVunG0qdl...,Mechanical Engineering,India,"9,12,2,8,15,3",https://docs.google.com/document/d/1KlugFQb4bO...,2020.0
16,16.0,201821029070,Published,"MS. MUSKAN PARAKH, MR. OMKAR KUMBHAR, DR. G. S...",ATC-SYSTEM: ADVANCED TRAFFIC CONTROL SYSTEM BY...,"MS. MUSKAN PARAKH, MR. OMKAR KUMBHAR, DR. G. S...",02-08-2018,2/7/2020,06/2020,"JSPM, Pune",https://drive.google.com/file/d/1e_h37DBnHJG3d...,Civil Engineering,India,"11,9,3,16,13",https://docs.google.com/document/d/1pDfDnzZIwe...,2020.0
17,17.0,201921053887,Published,"Mrunal N Annadate, Manoj S. Nagmode",Method For Detection Of Heart Abnormality In U...,"Mrunal N Annadate, Manoj S. Nagmode",26-12-2019,21-02-2020,08/2020,Dr.Vishwanath Karad MIT WORLD PEACE UNIVERSITY...,https://drive.google.com/file/d/1MOSVfxF13-HfU...,Electrical and Electronics Engineering,India,"3,8,10,12,17",https://docs.google.com/document/d/1NztlaGyuvb...,2020.0
18,18.0,201921051414,Published,"Aditi Jahagirdar, Manoj Nagmode",SYSTEM AND METHOD FOR ABNORMAL EVENT DETECTION,"Aditi Jahagirdar, Manoj Nagmode",12-12-2019,31-01-2020,05/2020,Dr.Vishwanath Karad MIT WORLD PEACE UNIVERSITY...,https://drive.google.com/file/d/1du10e7q6Ajdzb...,Computer Engineering & Technology,India,"3,9,11,16,17",https://docs.google.com/document/d/1CtD94cvSUz...,2020.0
19,19.0,202041039531,Published,"Anita Nene, S. RAMACHANDRAN",Convex conical receiver with rim in concentrat...,"Anita Nene, S. RAMACHANDRAN",9/12/2020,9/25/2020,39/2020,Dr.Vishwanath Karad MIT WORLD PEACE UNIVERSITY...,https://drive.google.com/file/d/1OEr17fyReqFm3...,Mechanical Engineering,India,"7,9,12,13",https://docs.google.com/document/d/1Ci53sO_WDr...,2020.0
20,20.0,201821031879,Published,"Virendra V. Shete, Sunil B. Somani, Mangesh Gi...",System for multiple-fault diagnosis in digital...,"Mangesh Girish Islampurkar, Virendra V. Shete",25-08-2018,28-02-2020,09/2020,Dr.Vishwanath Karad MIT WORLD PEACE UNIVERSITY...,https://drive.google.com/file/d/1FNs1st7jECFgf...,Electrical and Electronics Engineering,India,"9,12,13,17",https://docs.google.com/document/d/1x_ziJjGRWl...,2020.0
21,21.0,202021039556,Published,"Mahesh B. Sonawane, Sumedh Y. Mhaske\r\n",ADIM- CLIMATE ZONE OF INDIA: ASSESSMENT OF DAY...,"Mahesh B. Sonawane, Sumedh Y. Mhaske",9/13/2020,9/25/2020,39/2020,Dr. Vishwanath Karad MIT-World Peace University,https://drive.google.com/file/d/1FN14IrPGNVfvV...,Civil Engineering,India,"7,11,13,12",https://docs.google.com/document/d/1yjUUxzzV1o...,2020.0
22,22.0,202021008223,Published,"Vandana Jagtap, Shilpa Pimpalkar, Kumudini Mun...",IOT Based Water Dispensing Apparatus,"Vandana Jagtap, Shilpa Pimpalkar, Kumudini Mun...",2/26/2020,5/22/2020,21/2020,Dr. Vishwanath Karad MIT-World Peace University,https://drive.google.com/file/d/1Y1bjfDRS79DjE...,Computer Engineering & Technology,India,"6,9,12,13,11",https://docs.google.com/document/d/13T-WUCjcfT...,2020.0
23,23.0,201921002719,Published,"Swati Changdeo Jagdale, Anuruddha Rajaram Chab...",Stable topical composition comprising tretinoi...,"Swati Changdeo Jagdale, Anuruddha Rajaram Chab...",1/23/2019,7/31/2020,31/2020,Dr. Vishwanath Karad MIT-World Peace University,https://drive.google.com/file/d/1Ju4Nna2BEWbyw...,School of Pharmacy,India,NaN,NaN,2020.0
24,24.0,201921019148,Published,"Choudhari Ganesh, Choudhari Vishnu, Kuchekar B...",Liquid Composition Comprising Multiple Active ...,"Choudhari Ganesh, Choudhari Vishnu, Kuchekar B...",5/14/2019,12/4/2020,49/2020,Dr. Vishwanath Karad MIT-World Peace University,https://drive.google.com/file/d/1iz9cRcis2Lg_f...,School of Pharmacy,India,NaN,NaN,2020.0
26,25.0,2021106391,Granted,Arti Khaparde; Yogita Gajare,HIGHER ORDER DESIGN OF DIGITAL CIFB SIGMA DELT...,Dr. Vishwanath Karad MIT World Peace Universit...,8/21/2021,11/10/2021,2021106391,Dr.Vishwanath Karad MIT WORLD PEACE UNIVERSITY...,https://drive.google.com/file/d/1Itd31RhsFjVzN...,Electrical and Electronics Engineering,Australia,"9,12,7,13,4,11",https://docs.google.com/document/d/1VovDed0nwX...,2021.0
27,26.0,2021106258,Granted,"Saoji, Swapna; Pande, Milind",A SYSTEM FOR MANAGING AND AUTOMATING ACTIVITIE...,Dr. Vishwanath Karad MIT World Peace Universit...,20-08-2021,11/10/2021,2021106258,Dr.Vishwanath Karad MIT WORLD PEACE UNIVERSITY...,https://drive.google.com/file/d/14KVI_LLBvCZSC...,Computer Engineering & Technology,Australia,"8,9,10,12,4,11,17",https://docs.google.com/document/d/1PQvV20PO4m...,2021.0
28,27.0,2021106257,Granted,"Dr. Prasad Khandekar, Dr. Shaila Subbaraman, P...",A BOUNDARY CIRCUIT FOR INTERFACING AN ADIABATI...,Dr. Vishwanath Karad MIT World Peace Universit...,20-08-2021,11/10/2021,2021106257,Dr.Vishwanath Karad MIT WORLD PEACE UNIVERSITY...,https://drive.google.com/file/d/1mtFeSvt6FcGzc...,Electrical and Electronics Engineering,Australia,"7,9,12,13,8,4,17",https://docs.google.com/document/d/1A0EI9RDPKw...,2021.0
29,28.0,2021106275,Granted,Dr. Milind Pande ; Mr. Varad Vivek Vishwarupe;...,A ZONE-SPECIFIC WEATHER MONITORING SYSTEM,Dr. Vishwanath Karad MIT World Peace Universit...,21-08-2021,11/10/2021,2021106275,Dr.Vishwanath Karad MIT WORLD PEACE UNIVERSITY...,https://drive.google.com/file/d/1XRJJP9wmsXZQe...,Computer Engineering & Technology,Australia,"13,11,9,6,17,2,3",https://docs.google.com/document/d/1KSGBJ8TfS9...,2021.0
30,29.0,2021105340,Granted,Dr. Ganesh Ingle; Sudhir P Patil; Mahesh V Tat...,A MOULD FOR PREPARING ADDITIVES FOR STABILIZAT...,Dr. Vishwanath Karad MIT World Peace Universit...,8/12/2021,11/3/2021,2021105340,Dr.Vishwanath Karad MIT WORLD PEACE UNIVERSITY...,https://drive.google.com/file/d/1ZgmS5-Pz2XHUl...,Civil Engineering,Australia,"9,11,13,12,15,2",https://docs.google.com/document/d/10ZKCVQjImr...,2021.0
31,30.0,2021106248,Granted,"Sonawane, Mahesh; Mhaske, Sumedh",A METHOD FOR ASSESSING CLIMATE BASED ON ILLUMI...,Dr. Vishwanath Karad MIT World Peace Universit...,20-08-2021,11/17/2021,2021106248,Dr.Vishwanath Karad MIT WORLD PEACE UNIVERSITY...,https://drive.google.com/file/d/1T1tS7V31ybmAP...,Civil Engineering,Australia,"13,9,7,11,3,6,15",https://docs.google.com/document/d/1gy4PrTzWoh...,2021.0
32,31.0,2021105197,Granted,"Kulkarni, Mrudula; Mainkar, Prakash",A THERMAL CONDUCTIVITY METER FOR DETERMINING T...,Dr. Vishwanath Karad MIT World Peace Universit...,8/10/2021,11/3/2021,2021105197,Dr.Vishwanath Karad MIT WORLD PEACE UNIVERSITY...,https://drive.google.com/file/d/1piT2LEDpe1a6P...,Civil Engineering,Australia,"9,11,12,13,7,8,15",https://docs.google.com/document/d/1fllg8vzApz...,2021.0
33,32.0,2021105196,Granted,Balaso Nivrutti Jagdale; Shounak Rushikesh Sug...,FAKE NEWS SCANNER SYSTEM EMBEDDED IN SMARTWATC...,Dr. Vishwanath Karad MIT World Peace Universit...,8/10/2021,10/27/2021,2021105196,Dr.Vishwanath Karad MIT WORLD PEACE UNIVERSITY...,https://drive.google.com/file/d/1lm5fDrdU9k8XF...,Computer Engineering & Technology,Australia,"16,4,9,17,12,15",https://docs.google.com/document/d/1vry3D-r0n2...,2021.0
34,33.0,2021105342,Granted,"Sarode, Parchi; Pattabiraman, V and T. R, Reshmi",MULTIVARIATE QUERY RESPONSE METHOD FOR DATA AG...,Dr. Vishwanath Karad MIT World Peace Universit...,8/12/2021,10/20/2021,2021105342,Dr.Vishwanath Karad MIT WORLD PEACE UNIVERSITY...,https://drive.google.com/file/d/1kHt4sWH_AqObP...,Computer Engineering & Technology,Australia,"9,12,13,17,4,10,11",https://docs.google.com/document/d/1U8C3Yw8ktM...,2021.0
35,34.0,2021106276,Granted,"Ingavale, Aniket; Sabne, Niranjan; Bhandare, K...","A SYSTEM AND METHOD FOR MONITORING, COMMUNICAT...",Dr. Vishwanath Karad MIT World Peace Universit...,21-08-2021,11/10/2021,2021106276,Dr.Vishwanath Karad MIT WORLD PEACE UNIVERSITY...,https://drive.google.com/file/d/1CGT5SKnxDVEu6...,Computer Engineering & Technology,Australia,"7,9,11,12,13,16,17",https://docs.google.com/document/d/1lFi0TVYBcD...,2021.0
36,35.0,2021106261,Granted,"Dr. Lalit Kulkarni, Balaso Jagdale, Sumedha Si...",A SYSTEM EMPLOYING AN OPPORTUNISTIC NETWORK FO...,Dr. Vishwanath Karad MIT World Peace Universit...,20-08-2021,11/10/2021,2021106261,Dr.Vishwanath Karad MIT WORLD PEACE UNIVERSITY...,https://drive.google.com/file/d/1ohIc8WTeObx8U...,Computer Engineering & Technology,Australia,"3,9,11,16,17",https://docs.google.com/document/d/1sgrVdm8EW-...,2021.0
37,36.0,2021106262,Granted,Sumedha Sirsikar ; Abhishek Chunawale ; Prasad...,A BRAIN SIGNAL CONTROLLED INTELLIGENT WHEELCHA...,Dr. Vishwanath Karad MIT World Peace Universit...,20-08-2021,11/10/2021,2021106262,Dr.Vishwanath Karad MIT WORLD PEACE UNIVERSITY...,https://drive.google.com/file/d/1uXnLCap3Jri9T...,Computer Engineering & Technology,Australia,"3,9,10,11,17",https://docs.google.com/document/d/1YBwEmZ5C1D...,2021.0
38,37.0,2021106259,Granted,"Tiple, Bhavana; Atkar, Ashish; Baraskar, Samik...",METHOD FOR PROVIDING INFORMATION ASSOCIATED WI...,Dr. Vishwanath Karad MIT World Peace Universit...,20-08-2021,11/17/2021,2021106259,Dr.Vishwanath Karad MIT WORLD PEACE UNIVERSITY...,https://drive.google.com/file/d/1XlfDpDuVaWjk7...,Computer Engineering & Technology,Australia,"3,4,10,11,17",https://docs.google.com/document/d/1wSIaAc_ETY...,2021.0
39,38.0,2020104298,Granted,"DAMODAR ANUSE, ALWIN; SANDIP KUTE, RUPALI; VIJ...",CENSORING ONLINE SOCIAL MEDIA PLATFORM CONTENT...,"DAMODAR ANUSE, ALWIN; SANDIP KUTE, RUPALI; VIJ...",12/23/2020,3/3/2021,2020104298,Dr.Vishwanath Karad MIT WORLD PEACE UNIVERSITY...,https://drive.google.com/file/d/1e_Hcw4f6Rh78N...,Computer Engineering & Technology,Australia,"16,9,10,4,17",https://docs.google.com/document/d/1888nwqO1gY...,2021.0
40,39.0,2021106657,Granted,Dr. Pradnya S. Kulkarni,Pixel N-gram Image Representation System for M...,Dr. Pradnya S. Kulkarni,8/23/2021,11/17/2021,2021106657,Dr.Vishwanath Karad MIT WORLD PEACE UNIVERSITY...,https://drive.google.com/file/d/1X7xU9vaOxq82a...,Computer Engineering & Technology,Australia,"3,9,10,12,17",https://docs.google.com/document/d/17raXFA9SR3...,2021.0
41,40.0,2021105861,Granted,"Sukhada Bhingarkar, Deven Shah\r\n",Method For Detecting Edos Attack In Virtual Se...,"Sukhada Bhingarkar, Deven Shah\r\n",8/18/2021,11/17/2021,2021105861,Dr.Vishwanath Karad MIT WORLD PEACE UNIVERSITY...,https://drive.google.com/file/d/1DQuaV7hGQbpVA...,Computer Engineering & Technology,Australia,"9,12,16,17",https://docs.google.com/document/d/1c_YQE5cpQZ...,2021.0
42,41.0,2021104405,Granted,Dr.Anita Nene; Nabharun Bhattcharya ; Garv Set...,CONDUCTING LIQUID VORTEX DC MOTOR,Dr. Vishwanath Karad MIT World Peace University,21-07-2021,8/11/2021,2021104405,Dr.Vishwanath Karad MIT WORLD PEACE UNIVERSITY...,https://drive.google.com/file/d/1vBm45On6Ptrm7...,Mechanical Engineering,Australia,"7,9,12,13,17",https://docs.google.com/document/d/1na1E02nY9q...,2021.0
43,42.0,2021105191,Granted,"Ganesh Kakandikar , Anil Mashalakar , Omkar Ku...",A MICRO-FORMING DEVICE,Dr. Vishwanath Karad MIT World Peace Universit...,8/10/2021,11/3/2021,2021105191,Dr.Vishwanath Karad MIT WORLD PEACE UNIVERSITY...,https://drive.google.com/file/d/1HSpa_bP7vuDRp...,Mechanical Engineering,Australia,"9,12,13,17",https://docs.google.com/document/d/1cnAbOmHG_B...,2021.0
44,43.0,2021105195,Granted,Amit Jomde; Vivekanand A Naikwadi ; Tamkhade P...,A VARIABLE FLOW RADIATOR FOR A VEHICLE,Dr. Vishwanath Karad MIT World Peace Universit...,8/10/2021,10/27/2021,2021105195,Dr.Vishwanath Karad MIT WORLD PEACE UNIVERSITY...,https://drive.google.com/file/d/1t0yzaZYTgAsOv...,Mechanical Engineering,Australia,"7,9,11,12,13",https://docs.google.com/document/d/1JsA-Kp4JOm...,2021.0
45,44.0,2021106269,Granted,"Ganesh Kakandikar , Anil Mashalakar , Omkar Ku...",FLEXIBLE DEEP DRAWING ARRANGEMENT,Dr. Vishwanath Karad MIT World Peace Universit...,21-08-2021,11/10/2021,2021106269,Dr.Vishwanath Karad MIT WORLD PEACE UNIVERSITY...,https://drive.google.com/file/d/1aUIACa19WjG5I...,Mechanical Engineering,Australia,"9,12,13,8,11,4",https://docs.google.com/document/d/1MaA42xGDa5...,2021.0
46,45.0,2021107065,Granted,"Chaudhari, Bharat S.; Kukade, Shweta; Patil, R...",OPTIMAL RESOURCE ALLOCATION IN NEXT-GENERATION...,Dr.Vishwanath Karad MIT-World Peace University...,8/24/2021,11/24/2021,2021107065,Dr.Vishwanath Karad MIT WORLD PEACE UNIVERSITY...,https://drive.google.com/file/d/1kL6MQys3W3tBs...,Electrical and Electronics Engineering,Australia,"9,12,13,8,11,4,17",https://docs.google.com/document/d/1Hn-3hIvs4w...,2021.0
47,46.0,202021051007,Published,"Ganesh Kakandikar, Anil Mashalkar, Omkar Kulka...",A MICRO-FORMING DEVICE,"Ganesh Kakandikar, Anil Mashalkar, Omkar Kulka...",11/24/2020,1/29/2021,05/2021,Dr.Vishwanath Karad MIT WORLD PEACE UNIVERSITY...,https://drive.google.com/file/d/1doQCBBro0xiA_...,Mechanical Engineering,India,"9,12,8,13,4",https://docs.google.com/document/d/1kHmqnXWAGB...,2021.0
48,47.0,202121031924,Published,"Deepak Popat Hujare, Paresh Sunil Patel, Giris...",INBUILT TWO TIER JACK ASSEMBLY FOR VEHICLE,Dr. Vishwanath Karad MIT World Peace Universit...,7/15/2021,8/27/2021,35/2021,Dr.Vishwanath Karad MIT WORLD PEACE UNIVERSITY...,https://drive.google.com/file/d/1DqEa165a9YCHl...,Mechanical Engineering,India,"9,7,8,11,12,3",https://docs.google.com/document/d/15RQpl4NPt6...,2021.0
49,48.0,202121008267,Published,"Jadhav, Nathrao; Chaudhari, Bharat",OPTIMIZED FIVE PORT NON-BLOCKING OPTICAL ROUTE...,Dr. Vishwanath Karad MIT World Peace University,2/26/2021,4/23/2021,17/2021,Dr.Vishwanath Karad MIT WORLD PEACE UNIVERSITY...,https://drive.google.com/file/d/1EqKgPQ6mvJyd2...,Electrical and Electronics Engineering,India,"9,7,11,12,13,4",https://docs.google.com/document/d/1oFjMoc0vm_...,2021.0